[package]
name = "bindgen"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib_test = {path = "../lib_test"}
interoptopus = "0.13.6"
interoptopus_backend_csharp = "0.13.6"